# استفاده از ایمیج رسمی مای‌اس‌کیوال
FROM mysql:8.0

# تنظیم متغیرهای محیطی برای پسورد و دیتابیس اولیه
ENV MYSQL_ROOT_PASSWORD=my-secret-pw
ENV MYSQL_DATABASE=test_db
ENV MYSQL_USER=user1
ENV MYSQL_PASSWORD=pass1

# باز کردن پورت پیش‌فرض
EXPOSE 3306
